### ISSUE TITLE
Migrate metabb from nine.buildbot.net to buildbot.buildbot.net

### ISSUE THREAD

**Issue by seankelly** [buildbot/buildbot-infra#212]
Migrate the meta-buildbot instance from nine.buildbot.net back to buildbot.buildbot.net. The nine subdomain was for testing nine but that is now the primary and only instance. buildbot.buildbot.net redirects to nine.buildbot.net and I think that should be flipped. It's a 302 redirect so it's not permanent and safe to switch.

- [x] Get new certificates.
- [ ] Add nine -> buildbot redirect.
- [x] Update GitHub hook.

**Comment by tardyp** [comment]
fine for me. Need to take care of the SSL certs, and the github hooks.

**Comment by tardyp** [comment]
also if we move the jail to 'buildbot' instead of nine, we need to transfer the sqlite db (1.8GB)
