### ISSUE TITLE
https://docs.buildbot.net ssl certificate is out of date

### ISSUE THREAD

**Issue by Mic92** [buildbot/buildbot-infra#276]
The certificate expired on the 15/04/2024

**Comment by djmitche** [comment]
@p12tic ^^ anything I can do to help?

**Comment by verm** [comment]
Well I tried to fix it and jumped down a crazy rabbit hole trying to figure out how this was setup haha.

Anyway I forgot to switch to an LE staging environment so I've been blocked as the limit is 5 failed requests per hour I think it might work after the update. We'll see.

**Comment by verm** [comment]
Okay well that was a waste of time.  The DNS for docs.buildbot.net has been changed I'm guessing this is part of @p12tic changing to Docker.

**Comment by djmitche** [comment]
Thanks for looking! Maybe the LE update isn't running..

**Comment by djmitche** [comment]
It is an LE certificate, so perhaps whatever was broken retried and finally fixed itself..
